kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv01
spec:
  capacity: # defines the capacity of PV we are creating
    storage: 10Gi # the amount of storage we are trying to claim
  accessModes: # defines the rights of the volume we are creating
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data01" # path to which we are creating the volume

