apiVersion: v1
kind: Pod
metadata:
  name: test-configmap
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "printenv"]
      image: ubuntu
      envFrom:
        - configMapRef:
            name: demo-config
